spring:
  application:
    name: Company-TECH
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Jayxunbey2003
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelogMaster.xml
server:
  port: 8081
secret:
  key: ApeVFjUOyTmk7XYwgcYwIEsix1mALAsQhftYQqWHE8P6kcnqbZv0Uxj9HduKEvjXzz0sVYCG0ZjSBtmxadtAiQ==